export const MOTION_REGISTRY = {
  FADE: {
    IN: "MODULE::ANIMATIONS:FADE:IN",
  },
  TEXT: {
    DEFAULT: "MODULE::ANIMATIONS:TEXT:DEFAULT",
  },
  SLIDER: "MODULE::ANIMATIONS:SLIDER",
  SLIDE: {
    IN: "MODULE::ANIMATIONS:SLIDE:IN",
  },
};
