export const MOTION_REGISTRY = {
  FADE: {
    IN: "MODULE::ANIMATIONS:FADE:IN",
  },
  TEXT: {
    DEFAULT: "MODULE::ANIMATIONS:TEXT:DEFAULT",
  },
  SLIDER: "MODULE::ANIMATIONS:SLIDER",
  SLIDE: {
    IN: "MODULE::ANIMATIONS:SLIDE:IN",
  },
  OPEN: {
    FILL: "MODULE::ANIMATIONS:OPEN:FILL",
  },
  EMERGE: "MODULE::ANIMATIONS:EMERGE",
  SIMPLE: {
    EMERGE: "MODULE::ANIMATIONS:SIMPLE:EMERGE",
  },
  SVG: {
    DRAWN: "MODULE::ANIMATIONS:SVG:DRAWN",
  },
};
