export const PORTFOLIO_REGISTRY = {
  MAIN: Symbol.for("MODULE::CORE:PORTFOLIO"),
  CONTROLLER: Symbol.for("MODULE::CORE:PORTFOLIO:CONTROLLER"),
  SERVICE: Symbol.for("MODULE::CORE:PORTFOLIO:SERVICE"),
  USE_CASE: {
    SELECT: {
      ALL: Symbol.for("MODULE::CORE:PORTFOLIO:USE_CASE:SELECT:ALL"),
    },
  },
};
