export const PORTFOLIO_REGISTRY = {
  MAIN: Symbol.for("MODULE::CORE:PORTFOLIO"),
  CONTROLLER: Symbol.for("MODULE::CORE:PORTFOLIO:CONTROLLER"),
  SERVICE: Symbol.for("MODULE::CORE:PORTFOLIO:SERVICE"),
};
